### PR TITLE
DNM : Upmerge 17 10 2019

### PR DESCRIPTION
**Pull request by ioannisg**
In progress - do not merge.

### CODE REVIEW

**Comment by ioannisg** [comment]
Thanks @SebastianBoe for helping out resolving the conflicts

**Comment by ioannisg** [comment]
@pdunaj  @hakonfam can you test this and provide feedback?

**Comment by carlescufi** [comment]
> @pdunaj @hakonfam can you test this and provide feedback?

They should test the PR in -nrf.

**Comment by ioannisg** [comment]
> 
> 
> > > @pdunaj @hakonfam can you test this and provide feedback?
> > 
> > 
> > They should test the PR in -nrf.
> 
> Hi @carlescufi , sure. @MarekPieta will check it and put a comment.

https://github.com/NordicPlayground/fw-nrfconnect-nrf/pull/1306

**Comment by MarekPieta** [comment]
Hi,
I noticed dts problem for nrf_desktop boards using SPI. It is displayed when running cmake:
`Exception: /soc/spi@40003000/pwa3212@0 defines parent /soc/spi@40003000 as bus master, but /soc/spi@40003000 is not configured as bus master in binding`. The issue did not occurr before the upmerge.

**Comment by MarekPieta** [comment]
We will have to update DTS for our boards and definitions related to DTS in our drivers. I will take care of it. Should I add the changes to this PR ?

After applying changes to DTS, it seems like everything works fine for us.

**Comment by carlescufi** [comment]
> We will have to update DTS for our boards and definitions related to DTS in our drivers. I will take care of it. How can I add these changes to the PR?

I assume those are in -nrf @MarekPieta ? just send the commits to the corresponding -nrf PR

**Pull request merged**
