### PR TITLE
net: tcp: Bring essential TCP fixes from upstream

### PR DESCRIPTION
**Pull request by rlubos**
It was requested by the Community to incorporate latest TCP fixes into NCS 2.0 release.

### CODE REVIEW

**Comment by rlubos** [comment]
Dear reviewers, I know it's not your area, but I still need 2 approvals to get this in, and there's not really anyone beside me that could review this. The commits are just cherry-picks from upstream, requested by upstream NCS users.

**Comment by rlubos** [comment]
@AndreyDodonov-EH FYI, the commit list should be complete, but please let me know if I missed something (I did not include tests in the list on purpose).

**Comment by AndreyDodonov-EH** [comment]
> @AndreyDodonov-EH FYI, the commit list should be complete, but please let me know if I missed something (I did not include tests in the list on purpose).

@rlubos 
1. I think you also fixed packet leak in `net_shell.c` ?
2. I find your DNS fix also important: https://github.com/zephyrproject-rtos/zephyr/pull/42321
(though that's not strictly TCP, but I think it makes sense to integrate it nevertheless)
3. That's not TCP at all, but I found this fix quite critical: https://github.com/zephyrproject-rtos/zephyr/pull/44090, would be happy if it also lands in 2.0 and in Zephyr. It was causing spontaneous reboots when logging a lot, which was hard to track. 
May be makes sense to merge it and backport it in a separate PR.

**Comment by rlubos** [comment]
Packet leak fix in net_shell was brought with the recent upmerge.

> May be makes sense to merge it and backport it in a separate PR.

Yes, let's focus on networking stuff in this PR.

**Review by anangl — APPROVED** [review]

**Comment by AndreyDodonov-EH** [comment]
@rlubos 
I'd like to share intermediate test results.

I checked out complete networking (sybsys/net and include) from your branch.

Everything seems fine, except for downloading - sometimes when downloading big files I just receive less data on HTTP level.
(E.g. requesting 1 MB and receiving 800 KB or so). 

I'll try to reproduce it based on big_http_download sample on QEMU and not just on target (where there is some packet loss definitely, it's medium-quality Wi-Fi).
In terms of configuration, I don't set RX window explicitly or buffer count (so it remains default 36).

Once I have a tangible example to reproduce, I'll share it here.

**Pull request merged**
