### PR TITLE
synchronize ZMS with upstream version

### PR DESCRIPTION
**Pull request by rghaddab**
This PR synchronizes ZMS with the merged upstream version and fixes some style comments addressed as a followup PR

### CODE REVIEW

**Review by tomi-font — APPROVED** [review]

**Review by omkar3141 — APPROVED** [review]

**Review by miha-nordic — APPROVED** [review]

**Review by miha-nordic — APPROVED** [review]

**Review by tomi-font — APPROVED** [review]

**Comment by rghaddab** [comment]
@rlubos All checks are green here and already got the approvals before rebase

**Review by de-nordic — APPROVED** [review]

**Comment by tomi-font** [comment]
@rghaddab Has downstream CI been run on a `sdk-nrf` PR? (I think it's needed.)

**Comment by rghaddab** [comment]
> @rghaddab Has downstream CI been run on a `sdk-nrf` PR? (I think it's needed.)

In progress :
https://github.com/nrfconnect/sdk-nrf/pull/18266

**Review by omkar3141 — APPROVED** [review]

**Comment by rghaddab** [comment]
Checks are green in the sdk-nrf PR
https://github.com/nrfconnect/sdk-nrf/pull/18266

**Pull request merged**
