### PR TITLE
Cherrypick upstream USB fixes

### PR DESCRIPTION
**Pull request by bjda**
Gets rid of some USB issues for connectivity_bridge application

### CODE REVIEW

**Comment by emob-nordic** [comment]
Those commits later become a part of [#23307](https://github.com/zephyrproject-rtos/zephyr/pull/23307). Don't You want all those fixes?

**Comment by bjda** [comment]
Since I'm not sure if there could be dependencies or interactions between the other commits in that PR and any other changes to Zephyr since the last upmerge, I limited it to those that are known to fix some issues with connectivity_bridge. @nordic-auko , feel free to chime in on whether the whole PR should be included.

**Comment by nordic-auko** [comment]
> 
> 
> Since I'm not sure if there could be dependencies or interactions between the other commits in that PR and any other changes to Zephyr since the last upmerge, I limited it to those that are known to fix some issues with connectivity_bridge. @nordic-auko , feel free to chime in on whether the whole PR should be included.

These two commits fixed the issues I saw with USB MSC (USB device not responding properly to unsupported SCSI commands), so they should be included here. The three other commits I believe are part of an ongoing revamp of the USB MSC implementation. 

I tested both the set of 2 commits and the set of all 5 commits separately and have not seen any issues. I don't believe there are any inter dependencies, but I can't say if the set of 3 commits fixes separate problems not seen by me

**Comment by bjda** [comment]
Rebased on ncs master

**Pull request merged**
