### PR TITLE
cmake: move partition manager to nrf repo

### PR DESCRIPTION
**Pull request by hakonfam**
Move all partition manager related code to the nrf repo.
This because no part of this is upstream and all the
documentation is kept in the nrf repo.

Signed-off-by: Håkon Øye Amundsen <haakon.amundsen@nordicsemi.no>

### CODE REVIEW

**Comment by oyvindronningstad** [comment]
Also edit cmake/reports/CMakeLists.txt. There might be other places as well.

**Comment by hakonfam** [comment]
> Also edit cmake/reports/CMakeLists.txt. There might be other places as well.

Fixed

```
➜  zephyr git:(move-pm) ✗ rg -t cmake -i "partition_manager"
cmake/app/boilerplate.cmake
565:include(${ZEPHYR_BASE}/../nrf/cmake/partition_manager.cmake)

cmake/reports/CMakeLists.txt
25:  ${ZEPHYR_BASE}/../nrf/scripts/partition_manager_report.py
27:  "$<$<NOT:$<TARGET_EXISTS:partition_manager>>:--quiet>"
➜  zephyr git:(move-pm) ✗ 
```

**Comment by hakonfam** [comment]
A bit of catch-22 situation regarding CI, as it depends on the updated version of fw-nrfconnect-nrf, but that again depends on this PR for the manifest file, not sure how to proceed.

**Comment by SebastianBoe** [comment]
I agree that we should maintain PM in 'nrf' until it (or some version of it) is upstreamed. This will allow us to work in a single repo as much as possible.

**Comment by SebastianBoe** [comment]
> A bit of catch-22 situation regarding CI, as it depends on the updated version of fw-nrfconnect-nrf, but that again depends on this PR for the manifest file, not sure how to proceed.

Should we merge 'nrf' with a reference to the PR, and then after this CI is green and merged, do a new PR to change from ref to SHA in nrf?

**Pull request merged**
