### PR TITLE
[DNM] Upmerge 140619

### PR DESCRIPTION
**Pull request by ioannisg**
Upmerging from upstream/master

### CODE REVIEW

**Comment by ioannisg** [comment]
Happy testing.
One thing we need to do, as discussed with @SebastianBoe is to account for the mmbedtls being split-out from upstream/zephyr into an own repo.

**Comment by ioannisg** [comment]
@pdunaj @hakonfam could you also evaluate this upmerge?

**Comment by hakonfam** [comment]
Get this failure on `http_application_update`

```
FAILED: mcuboot/CMakeFiles/mcuboot_app.dir/os.c.obj 
ccache /home/haam/Downloads/gcc-arm-none-eabi-7-2018-q2-update/bin/arm-none-eabi-gcc -DBUILD_VERSION=v1.14.99-ncs2-rc1-277-gf69d8d61a934
 -DKERNEL -DNRF9160_XXAA -DUSE_PARTITION_MANAGER=1 -D_FORTIFY_SOURCE=2 -D__ZEPHYR__=1 -I/home/haam/ncs/mcuboot/boot/zephyr/include -I/ho
me/haam/ncs/mcuboot/boot/zephyr/targets -I/home/haam/ncs/mcuboot/boot/bootutil/include -I/home/haam/ncs/zephyr/kernel/include -I/home/ha
am/ncs/zephyr/arch/arm/include -I/home/haam/ncs/zephyr/include -I/home/haam/ncs/zephyr/include/drivers -Imcuboot/zephyr/include/generate
d -I/home/haam/ncs/zephyr/soc/arm/nordic_nrf/nrf91 -I/home/haam/ncs/zephyr/soc/arm/nordic_nrf/include -I/home/haam/ncs/zephyr/lib/libc/m
inimal/include -I/home/haam/ncs/zephyr/ext/hal/cmsis/Include -I/home/haam/ncs/zephyr/ext/hal/nordic/nrfx -I/home/haam/ncs/zephyr/ext/hal
/nordic/nrfx/drivers/include -I/home/haam/ncs/zephyr/ext/hal/nordic/nrfx/hal -I/home/haam/ncs/zephyr/ext/hal/nordic/nrfx/mdk -I/home/haa
m/ncs/zephyr/ext/hal/nordic/. -I/home/haam/ncs/nrf/include -isystem /home/haam/Downloads/gcc-arm-none-eabi-7-2018-q2-update/bin/../lib/g
cc/arm-none-eabi/7.3.1/include -isystem /home/haam/Downloads/gcc-arm-none-eabi-7-2018-q2-update/bin/../lib/gcc/arm-none-eabi/7.3.1/inclu
de-fixed -Og -nostdinc -imacros /home/haam/ncs/nrf/samples/nrf9160/http_application_update/build/mcuboot/zephyr/include/generated/autoco
nf.h -ffreestanding -fno-common -g -mthumb -mcpu=cortex-m33 -mfpu=fpv5-sp-d16 -mfloat-abi=hard -Wall -Wformat -Wformat-security -Wno-for
mat-zero-length -Wno-main -Wno-pointer-sign -Wpointer-arith -Wno-unused-but-set-variable -Werror=implicit-int -fno-asynchronous-unwind-t
ables -fno-pie -fno-pic -fno-strict-overflow -fno-reorder-functions -fno-defer-pop -ffunction-sections -fdata-sections -mabi=aapcs -marc
h=armv8-m.main+dsp -std=c99 -MD -MT mcuboot/CMakeFiles/mcuboot_app.dir/os.c.obj -MF mcuboot/CMakeFiles/mcuboot_app.dir/os.c.obj.d -o mcu
boot/CMakeFiles/mcuboot_app.dir/os.c.obj   -c /home/haam/ncs/mcuboot/boot/zephyr/os.c
/home/haam/ncs/mcuboot/boot/zephyr/os.c:27:10: fatal error: mbedtls/platform.h: No such file or directory
 #include <mbedtls/platform.h>
```

Haven't looked into it, but looks related to your comment further up.

**Comment by pdunaj** [comment]
Hi @ioannisg , sure.

At the moment build fails with
```
/home/pdunaj/work/ncs/nrf/subsys/bluetooth/services/hids.c: In function 'inp_rep_notify_all':
/home/pdunaj/work/ncs/nrf/subsys/bluetooth/services/hids.c:1117:13: warning: passing argument 2 of 'bt_gatt_notify_cb' makes integer from pointer without a cast
```
and its friends.

Generally CI should fail PR with manifest update as it should build our project.

**Comment by hakonfam** [comment]
FYI CI will also fail for http_application_update with manifest update in place :)

**Comment by hakonfam** [comment]
We need to figure out how to handle the mbedtls zephyr module. Will discuss with @tejlmand.

**Comment by ioannisg** [comment]
> 
> 
> Tested a few networking samples, seem to work fine.

We should not wait for more evidence to merge this, @rlubos , I suggest to get that in.

**Comment by rlubos** [comment]
@ioannisg Let's hold on a bit more, nrf_desktop tests failed, we need to sort it out first.

**Comment by rlubos** [comment]
I did a second upmerge on top of the previous one. Some Bluetooth fixes were introduces into master in a meantime, there's a chance they'll help with the nrf_desktop issues.

**Comment by rlubos** [comment]
@anangl @carlescufi Some of the DT symbols were not updated upstream, and we observe it now in the NCS CI. I've added two extra commits here, one fixing `qdec_nrfx` driver (IMO good to go), and on with fixes in nRF9160 nrfx config file. The latter one needs an update though - for now, I've only fixed what was required by the CI. The remaining symbols need to be updated as well I guess.

**Comment by rlubos** [comment]
Updated DT fixes as suggested F2F by @anangl

**Comment by rlubos** [comment]
The CI failures are inherited from upstream, merging.

**Pull request merged**
