### PR TITLE
[nrf noup] kconfig: move nRF Connect entry at the top

### PR DESCRIPTION
**Pull request by lemrey**
Move ~~nRF Connect SDK~~ Zephyr modules Kconfig entries at the top of the menu.
They are currently in a random spot.

### CODE REVIEW

**Comment by Qbicz** [comment]
I don't know original intent of @lemrey, but I think it looks better when a customer downloads Nordic nRF Connect SDK and see nRF-specific options on top, rather than 3rd from the bottom...

**Comment by lemrey** [comment]
@ioannisg no, it does not solve any practical issue. I think it's worth doing though, because the current situation is that that entry is in the middle of the top level menu, in what really is a random spot.

**Comment by ioannisg** [comment]
Could you take care of CI failure here, @lemrey ?

**Comment by lemrey** [comment]
@ioannisg I think the CI failures are unrelated to this PR and coming from upstream, not sure I can do much about them.

**Comment by ioannisg** [comment]
> 
> 
> @ioannisg I think the CI failures are unrelated to this PR and coming from upstream, not sure I can do much about them.

Would it make sense to re-check?

**Comment by lemrey** [comment]
Rebased, hopefully will be greener.

**Comment by ioannisg** [comment]
Looks like there were 2 tests failing in mps2_an385. We can try once more, or just merge this one, IMHO.

**Comment by lemrey** [comment]
Rebased. @SebastianBoe @carlescufi This patch moves the Kconfig entries of Zephyr modules at the top of the menu. The rationale is that they now appear in a random spot in the menu and have poor visibility.

**Comment by SebastianBoe** [comment]
Since there is no rush to get this in, wouldn't it be less paperwork to push this upstream, and then let it trickle down automatically?

Then we don't need to go through review here and upstream.

**Comment by carlescufi** [comment]
@lemrey agreed with @SebastianBoe. How about we try to push this upstream first?

**Comment by lemrey** [comment]
Will do.

**Comment by lemrey** [comment]
Pushed upstream.

**Pull request closed without merging**
