### PR TITLE
NCSDK-3401 Fix soc_flash_nrf sample.

### PR DESCRIPTION
**Pull request by LeHack**
Added harness config to sample in order for the sanitycheck tool
to run and understand whether the samples output is as expected.

Signed-off-by: Łukasz Hejnak <lukasz.hejnak@nordicsemi.no>

### CODE REVIEW

**Comment by mbolivar** [comment]
DNM until https://github.com/NordicPlayground/fw-nrfconnect-zephyr/pull/255 is in

**Comment by LeHack** [comment]
Added one more correction to also pass for nrf9160.

**Comment by lemrey** [comment]
I would have a more descriptive commit title if possible. The NCS JIRA task is not too useful when reading `git shortlog`, and neither is "fix sample". I suggest moving the NCS JIRA in the commit message, and use a more descriptive commit title e.g.: `samples: drivers: soc_flash_nrf: add test harness`.

**Comment by mbolivar** [comment]
History in this repository has been rewritten. Please rebase this PR.

**Comment by LeHack** [comment]
Rebased and updated commit message as suggested by @lemrey

**Comment by mbolivar** [comment]
Can I ask why this is `noup`? Looking at the patch, can't we merge it upstream?

**Comment by LeHack** [comment]
@mbolivar You're right. We initially assumed that it won't be useful for anyone outside Nordic, but upon further consideration it has some valid use cases in upstream as well.
I updated the tag as you can see, I will also prepare a PR to upstream in a moment.

**Comment by mbolivar** [comment]
> I updated the tag as you can see, I will also prepare a PR to upstream ~in a moment~:
> [zephyrproject-rtos/zephyr#21919](https://github.com/zephyrproject-rtos/zephyr/pull/21919)

Thank you!

**Pull request merged**
