### PR TITLE
[nrf formlist] dfu/boot: non-secure app support

### PR DESCRIPTION
**Pull request by nvlsianpu**
In non-secure Trustzone application dedicated flash non-secure
partition are used instead of regular one, which become secure
partition in Trustzone collaboration model.

Signed-off-by: Andrzej Puzdrowski <andrzej.puzdrowski@nordicsemi.no>

### CODE REVIEW

**Comment by hakonfam** [comment]
Could you reanme to use primary - secondary terminology as well?

**Comment by nvlsianpu** [comment]
@hakonfam ^^ ok will do

**Comment by nvlsianpu** [comment]
@hakonfam I replaced the terminology.

**Comment by nvlsianpu** [comment]
upstream mirror: https://github.com/zephyrproject-rtos/zephyr/pull/15413

**Comment by hakonfam** [comment]
Tested OK, please rebase and merge

**Pull request merged**
