### PR TITLE
Upmerge 16 01 2020

### PR DESCRIPTION
**Pull request by anangl**
Regular upmerge.

### CODE REVIEW

**Comment by carlescufi** [comment]
> Very nice.
> 
> ncs-loot before this PR (16 OOT patches):
> 
> ```
> - 7ddb13d5b748568adff7af00c93739591c767b60 [nrf noup] ci: Add Jenkins-based CI for zephyr
> - 4a309fb9baa47cef7242e9c46f951653321ae907 [nrf temphack] ci: work around sanitycheck issue
> - 171d34b1a4eb69f9bfe1cfc71a7455b923256a7f [nrf fromlist] tests/settings/functional/file: fix nRF targets
> - 5cac7c881ca6d1fc0ee51117704fa781091ddde8 [nrf toup] tests: drivers: counter: Add clock stabilization nRF
> - 213816bea3195b4ffc67225a0b690ad0049663ef [nrf toup] bluetooth: Selecting ENTROPY_GENERATOR for crypto
> - 7b202ccbbb77e912f1c540d090636f36d3d4e69a [nrf noup] bluetooth: controller: default to SPLIT architecture
> - cf6690e45a0627b5eb81536e921f72a6b175cabf [nrf toup] drivers: sensors: Fix compilation after HAL update
> - 4c24a6465be42be352ab58ed7552a4c11fc98de9 [nrf noup] include: net: add nRF91 extensions
> - 6bff2a99aba37ff5e74f48f26582927e1d49d60c [nrf noup] tree-wide: support NCS Partition Manager (PM) definitions
> - b0b08e853c5942bda1a2204e34101388cb4d3e8f [nrf temphack] include: arm: linker.ld: respect CONFIG_FW_INFO
> - 599fe14fb96889570d2e75d45a2295a0c00a15d7 [nrf noup] cmake: support CONFIG_MCUBOOT_BUILD_S1_VARIANT
> - b18076a653e17c6cab81508f948e418e434c80a1 [nrf temphack] net: lwm2m: REVERTME: add timestamp fields to several IPSO obj
> - 0892a7666d58c07dc9ad09542fbd5a5c0b415f0a [nrf temphack] west: REVERTME: Change variable used to find app dir
> - 26331ca5acd1b014ca82505f49d627b74c4bb021 [nrf fromtree] cmake: dts fixups
> - 717da49880048c5f7b0712eb9e31309c9dd7cdbd [nrf fromtree] drivers: uart_rtt: Handle PM callback properly
> - add574ca9f4dfda09a254ad3f2592ff1d1738f1d [nrf fromtree] drivers: wdt_nrfx: Handle PM callback properly
> ```
> 
> ncs-loot with this PR (11 OOT patches, but we also added 4 CI-related patches, so it's either 5 or 9 less OOT patches depending on how you count):
> 
> ```
> - 7ddb13d5b748568adff7af00c93739591c767b60 [nrf noup] ci: Add Jenkins-based CI for zephyr
> - 5cac7c881ca6d1fc0ee51117704fa781091ddde8 [nrf toup] tests: drivers: counter: Add clock stabilization nRF
> - 7b202ccbbb77e912f1c540d090636f36d3d4e69a [nrf noup] bluetooth: controller: default to SPLIT architecture
> - 4c24a6465be42be352ab58ed7552a4c11fc98de9 [nrf noup] include: net: add nRF91 extensions
> - 647c406b89b2e96eefe62c762a49c997f185d92c [nrf noup] codeowner: Add entry for .github and Jenkinsfile
> - eb4e78d449a37114da70439366e9134e574d9144 [nrf noup] ci: Adding Github-Actions:Backport-Bot
> - 85899db8a1ff578bc7bd4630110d844939be238d     [nrf noup] ci: adding common cron configuration
> - 804195cb13d312683804da7f8e9810da620b6716 [nrf noup] ci: Add coverage platform to Jenkinsfile
> - b1f2ff4bfef5b9dd157aa01c007f7e253f64702f [nrf temphack] tests/settings/functional/file: fix nRF targets
> - 53dd1828b87f2610e989bd54b8f6e97dd80dc2df [nrf noup] tree-wide: support NCS Partition Manager (PM) definitions
> - fb4ccd51821bb7ac654d5f00296d4a17f6fc6c99 [nrf noup] cmake: support CONFIG_MCUBOOT_BUILD_S1_VARIANT
> ```
> 
> You can cherry-pick the remaining OOT patches cleanly onto the new zephyr merge-base and get the same code (note to @carlescufi : this is how I rebase):
> 
> ```
> $ git checkout 2addfb4696  # this is the new zephyr merge-base
> $ git cherry-pick 7ddb13d5b748568adff7af00c93739591c767b60 5cac7c881ca6d1fc0ee51117704fa781091ddde8 7b202ccbbb77e912f1c540d090636f36d3d4e69a 4c24a6465be42be352ab58ed7552a4c11fc98de9 647c406b89b2e96eefe62c762a49c997f185d92c eb4e78d449a37114da70439366e9134e574d9144 85899db8a1ff578bc7bd4630110d844939be238d 804195cb13d312683804da7f8e9810da620b6716 b1f2ff4bfef5b9dd157aa01c007f7e253f64702f 53dd1828b87f2610e989bd54b8f6e97dd80dc2df fb4ccd51821bb7ac654d5f00296d4a17f6fc6c99
> ```
> 
> I've pushed the results of doing that here:
> 
> https://github.com/mbolivar/fw-nrfconnect-zephyr/tree/mergeup-261-rebase

Very impressive results everybody. I am really happy of the work we've done to keep OoT patches to a minimum, and the  results are here for everybody to see. A special mention to @mbolivar for his excellent ncs tools for patch management.

**Comment by anangl** [comment]
> #263
> 
> This patch is need, not sure how it should be added to the upmerge PR

I can add it to the commit titled "tree-wide: Fix inclusions of Zephyr headers" in https://github.com/NordicPlayground/fw-nrfconnect-nrf/pull/1750.

**Comment by anangl** [comment]
> #263
> 
> This patch is need, not sure how it should be added to the upmerge PR

@hakonfam I squashed it with commit "[nrf noup] tree-wide: support NCS Partition Manager (PM) definitions".

**Comment by hakonfam** [comment]
This patch is also needed

```
diff --git a/subsys/dfu/boot/mcuboot.c b/subsys/dfu/boot/mcuboot.c
index 1d40beb4a4..9189361c46 100644
--- a/subsys/dfu/boot/mcuboot.c
+++ b/subsys/dfu/boot/mcuboot.c
@@ -90,11 +90,11 @@ struct mcuboot_v1_raw_header {
 #define FLASH_AREA_IMAGE_PRIMARY DT_FLASH_AREA_IMAGE_0_ID
 #define FLASH_AREA_IMAGE_SECONDARY DT_FLASH_AREA_IMAGE_1_ID
 #endif /* CONFIG_TRUSTED_EXECUTION_NONSECURE */
-#endif /* USE_PARTITION_MANAGER */
 
 #ifdef DT_FLASH_AREA_IMAGE_SCRATCH_ID
 #define FLASH_AREA_IMAGE_SCRATCH DT_FLASH_AREA_IMAGE_SCRATCH_ID
 #endif
+#endif /* USE_PARTITION_MANAGER */
 
 #ifdef CONFIG_MCUBOOT_TRAILER_SWAP_TYPE
 #define SWAP_TYPE_OFFS(bank_area) ((bank_area)->fa_size -\
```

**Comment by hakonfam** [comment]
Verified http fota app, and hello world with b0, mcuboot and s1 variant of mcuboot.

**Comment by cvinayak** [comment]
@joerchan upstream the default is already Split controller.

**Comment by joerchan** [comment]
> @joerchan upstream the default is already Split controller.

Right. so no harm then. Only reason for this is that the "order" default changes. So could just put it explicitly

**Comment by anangl** [comment]
> @cvinayak can't we just put this one in upstream as well?
> `7b202ccbbb77e912f1c540d090636f36d3d4e69a [nrf noup] bluetooth: controller: default to SPLIT architecture`

> @joerchan upstream the default is already Split controller.

@joerchan @cvinayak Perhaps this commit should be reverted then, to align with upstream the way the split controller is selected?

**Comment by joerchan** [comment]
> @joerchan @cvinayak Perhaps this commit should be reverted then, to align with upstream the way the split controller is selected?

@anangl AFAIK this is needed because we redefine the menu. Which causes the default to change.

**Comment by nvlsianpu** [comment]
A few time I noticed that using smp_svr with BLE transport that after reboot using `sys_reboot(cold)` the BLE advertising request have been failing (not always, but in like 30% times).

**Comment by nvlsianpu** [comment]
^^
I investigate this more a and:
It is enough to connect to and the disconnect from `smp_svr` to trigger advertising error. Following loog shows whats happened:
```console
*** Booting Zephyr OS version 2.1.99  ***
Bluetooth initialized
Advertising successfully started


uart:~$ Connected
Disconnected (reason 0x13)
Advertising failed to start (rc -12)
```

Error code goes from there:
```C
			conn = bt_conn_add_le(param->id, BT_ADDR_LE_NONE);
			if (!conn) {
				return -ENOMEM;
			}
```
https://github.com/anangl/fw-nrfconnect-zephyr/blob/610aca9556f399b0fd4c605c091998d650c919f5/subsys/bluetooth/host/hci_core.c#L5948-L5951

**Comment by nvlsianpu** [comment]
^^looks like `conns` is not freed once disconnect.

**Comment by joerchan** [comment]
> ^^looks like conns is not freed once disconnected

@nvlsianpu @anangl This issue was fixed earlier today after @de-nordic reported it, cherry-picked here as: "[nrf fromtree] samples: smp_svr: Handle advertise start in [...]".

**Pull request merged**
