### PR TITLE
[nrf mergeup] Merge upstream up to commit 3b99b20

### PR DESCRIPTION
**Pull request by rlubos**
Introduce changes from upstream.

Signed-off-by: Sebastian Bøe <sebastian.boe@nordicsemi.no>

### CODE REVIEW

**Comment by Qbicz** [comment]
Hi @rlubos, I'm updating the code to APIs.

Please note currently this change also breaks all BLE services in NCS. (I will send a PR soon to take care of this)

**Comment by SebastianBoe** [comment]
ETA?

**Comment by Qbicz** [comment]
@SebastianBoe I estimate 1-2 hours. There are changes in USB, settings and BLE GATT.

**Comment by SebastianBoe** [comment]
@rlubos : Does this mean this will go in today?

**Comment by rlubos** [comment]
@Qbicz Note there's a manifest update PR in -nrf: https://github.com/NordicPlayground/fw-nrfconnect-nrf/pull/765
I've solved the GATT build issues there, but perhaps there are some runtime problems as well, I didn't verify that.

@SebastianBoe From my point of view this should go in as soon as we get the -nrf CI green. You can leave your +1 here :)

**Comment by Qbicz** [comment]
@rlubos Should I push rest of required changes to the manifest PR?

**Comment by rlubos** [comment]
@Qbicz Yes, feel free to push into my branch. Eventually we should squash all the fixes into the manifest update commit to retain bisectability.

**Pull request merged**
