### PR TITLE
[nrf temphack] bootloader: cmake: Fix kernel_elf target for multi-image

### PR DESCRIPTION
**Pull request by sigvartmh**
This will make sure that the `${IMAGE}kernel_elf` target is created for
secure bootloader(b0).

Signed-off-by: Sigvart Hovland <sigvart.hovland@nordicsemi.no>

### CODE REVIEW

**Comment by SebastianBoe** [comment]
This doesn't look right.

Why does b0 require kernel_elf?

I wonder if b0 should be using logical_target_for_zephyr_elf instead.

**Comment by hakonfam** [comment]
I agree @SebastianBoe , we will try to come up with something better

**Comment by carlescufi** [comment]
Please rebase on top of the current master

**Comment by sigvartmh** [comment]
Also agree :) hence [temphack] but I'll look with Håkon for another solution

**Pull request closed without merging**
