### PR TITLE
[nrf mergeup]: Merge fw-nrfconnect-zephyr up to commit bebc8dc

### PR DESCRIPTION
**Pull request by rlubos**

### CODE REVIEW

**Comment by rlubos** [comment]
Anyone has an idea what's wrong with the CI? Bamboo result is green, yet github claims it failed.

**Comment by SebastianBoe** [comment]
> build	20-Dec-2018 13:06:48	Compliance errors found
> build	20-Dec-2018 13:06:48	PR build failed
> 

Seems to that the bamboo "colour" should be red.

**Comment by SebastianBoe** [comment]
related?

> build	20-Dec-2018 13:02:01	FAILED: sam_e70_xplained/samples/application_development/code_relocation/test has unrecognized binary sections: ['_SRAM2_RODATA_SECTION_NAME', '_SRAM_TEXT_SECTION_NAME', '_SRAM_RODATA_SECTION_NAME', '_SRAM_DATA_SECTION_NAME', '_CUSTOM_SECTION_NAME2']
> build	20-Dec-2018 13:02:01	753 of 755 tests passed with 0 warnings in 2962 seconds
>

**Comment by rlubos** [comment]
Ok, it seems to be sanitycheck that fails on that sample. The problem is, that I get the same error when I run it locally on Zephyr master :| :
```
rolu@rolu-vm (master): [~/repos/zephyr]
$ ./scripts/sanitycheck -T samples/application_development/code_relocation/
JOBS: 8
Cleaning output directory /home/rolu/repos/zephyr/sanity-out
Selecting default platforms per test case
Building testcase defconfigs...
1 tests selected, 141 tests discarded due to filters
total complete:    1/   1  100%  failed:    0
FAILED: sam_e70_xplained/samples/application_development/code_relocation/test has unrecognized binary sections: ['_SRAM2_RODATA_SECTION_NAME', '_SRAM_TEXT_SECTION_NAME', '_SRAM_RODATA_SECTION_NAME', '_SRAM_DATA_SECTION_NAME', '_CUSTOM_SECTION_NAME2']
0 of 1 tests passed with 0 warnings in 12 seconds

```

**Comment by carlescufi** [comment]
@rlubos check if that is also present upstream. Otherwise we can live with it.

**Comment by rlubos** [comment]
It seems that the issue is inherited from upstream, see the shippable result from the PR that introduced the sample:
https://app.shippable.com/github/zephyrproject-rtos/zephyr/runs/28817/2/console
Even though the shippable marked the test as passed, you can see in the logs that exactly the same failure occurs. Agreed with @carlescufi to merge the PR anyway.

**Comment by SebastianBoe** [comment]
FYI: Upstream fix: https://github.com/zephyrproject-rtos/zephyr/pull/12231

**Pull request merged**
