### PR TITLE
Cplusplus fixups

### PR DESCRIPTION
**Pull request by erik-johnson-nimbelink**
A handful of fixes to libraries to make life in C++ land a little easier.

### CODE REVIEW

**Comment by erik-johnson-nimbelink** [comment]
I don't have access to the Jenkins build server's report, but it looks like it failed on the C++ guards. Is Jenkins currently able to build the master branch? It's baffling to me that it'd fail on something so basic, especially since so much other Zephyr code has those same guards already...

**Comment by carlescufi** [comment]
@erik-johnson-nimbelink thanks for the PR! Since we regularly upmerge from the upstream tree, would you mind sending this PR to https://github.com/zephyrproject-rtos/zephyr instead? Then we will get it next week or so as part of a regularly scheduled upmerge.

**Comment by erik-johnson-nimbelink** [comment]
Sure, will do.

**Comment by erik-johnson-nimbelink** [comment]
Looks like things are moving ahead upstream in Zephyr, so I'm happy to close this request out.

**Pull request closed without merging**
