### PR TITLE
Upmerge december

### PR DESCRIPTION
**Pull request by SebastianBoe**
Zephyr 2.1.0

### CODE REVIEW

**Comment by nvlsianpu** [comment]
child of https://github.com/NordicPlayground/fw-nrfconnect-nrf/pull/1647

**Comment by SebastianBoe** [comment]
@mbolivar : Done. Thank you for the detailed explanation.

**Comment by mbolivar** [comment]
> @mbolivar : Done. Thank you for the detailed explanation.

Thanks! As discussed elsewhere, I've got a rebase-and-then-cleanup branch started here:

https://github.com/mbolivar/fw-nrfconnect-zephyr/tree/mergeup-249-rebase-rewrite

I've squashed the CI commits, various multi-image patches, and various socket.h and net_ip.h commits together and reordered the results to ease reading. Our diff from upstream is smaller now and should be easier to deal with going forward.

We can upstream three of these patches [here](https://github.com/zephyrproject-rtos/zephyr/pull/21460), [here](https://github.com/zephyrproject-rtos/zephyr/pull/21463), and [here](https://github.com/zephyrproject-rtos/zephyr/pull/20208).

There are also three temphacks we can revert entirely or revert/rewrite in a cleaner way using zephyr_linker_sources().

**Comment by hakonfam** [comment]
> @SebastianBoe @hakonfam It is impossible to make DFU. When DFU server request to erase image collection bank, the primary bank is erased instead of secondary. This is something inherited from master, but I think better to fix it within upmerge patch series.
> 
> (Reproduced using smp_svr zephyr sample)

**Comment by hakonfam** [comment]
Verified local DFU (dfu candidate flashed to device) for mcuboot and app upgrade. Also verified dfu for `http_application_update` sample.

**Comment by SebastianBoe** [comment]
@nvlsianpu : Please re-asses your review.

**Pull request merged**
