### PR TITLE
[nrf mergeup] Merge upstream up to commit aeff0ee4ac

### PR DESCRIPTION
**Pull request by lemrey**
- Fix flashing of non-secure firmware (https://github.com/zephyrproject-rtos/zephyr/pull/13093)
- Fix missing `bluetooth_api` ref - ID (https://github.com/zephyrproject-rtos/zephyr/pull/13248)

There was one conflict in `net_ip.h` which I have resolved together with @rlubos
There was one conflict in `Kconfig.zephyr` which I have resolved by keeping both local and remote changes

CC: @carlescufi @ioannisg @joakimtoe

### CODE REVIEW

**Comment by ioannisg** [comment]
@lemrey any conflicts on this one? also, do you confirm buidling nrf9160 non-secure examples properly?

**Comment by lemrey** [comment]
> @lemrey any conflicts on this one? also, do you confirm buidling nrf9160 non-secure examples properly?

There was one conflict in `net_ip.h` which I have resolved together with @rlubos.
Yes, I have tested the non-secure examples and they flash properly :)

**Comment by tejlmand** [comment]
CI here is failing, cause it doesn't use correct revision from fw-nrfconnect-nrf repo.
This PR https://github.com/NordicPlayground/fw-nrfconnect-nrf/pull/453 refers to `pull/98/head` in manifest file, and is the CI to refer to.

**Comment by lemrey** [comment]
@carlescufi hold on, we might need a new commit.

**Comment by lemrey** [comment]
I have updated this PR to include a new commit needed to fix the documentation build.

**Comment by lemrey** [comment]
@tejlmand, @carlescufi The [PR](https://github.com/NordicPlayground/fw-nrfconnect-nrf/pull/453) to fw-nrfconnect-nrf updating the manifest is green.

**Pull request merged**
