### PR TITLE
[nrf noup] dts: Add nRF52810 to secureboot.overlay

### PR DESCRIPTION
**Pull request by oyvindronningstad**
This provides support for BOARD=nrf52810_pca10040.

### CODE REVIEW

**Comment by oyvindronningstad** [comment]
cc @hakonfam @ioannisg

**Comment by hakonfam** [comment]
While you are in here, could you re-order the file so that the order is a bit more intuitive?

**Comment by oyvindronningstad** [comment]
>While you are in here, could you re-order the file so that the order is a bit more intuitive?

Reordered and added nrf51822_qfaa which has the same flash size as qfac and is used in some boards (e.g. microbit)

**Comment by oyvindronningstad** [comment]
The Bamboo is marked as failed, but the linked run was green, I don't know how to fix it, can we merge anyways?

Anything preventing us merging this, @ioannisg and @hakonfam?

**Comment by hakonfam** [comment]
LGTM

**Comment by oyvindronningstad** [comment]
The build failure seems to be related to samples/application_development/code_relocation/test. This test fails on my branch, and on the nrf91 branch, but not on zephyr upsteam.

**Pull request merged**
