### PR TITLE
 [nrf mergeup] Merge upstream up to commit dee63e2

### PR DESCRIPTION
**Pull request by rlubos**
This upmerge introduces west, along with some bugfixes.

A single merge conflict encountered in `net_ip.h`, I've handled it myself.

Signed-off-by: Robert Lubos <robert.lubos@nordicsemi.no>

### CODE REVIEW

**Comment by lemrey** [comment]
This PR introduces one compiler warning in at least one sample in `fw-nrfconnect-nrf`, that's a bit odd. Let me investigate. Also are we not including these: https://github.com/zephyrproject-rtos/zephyr/pull/12406? :/

**Comment by rlubos** [comment]
@lemrey What do you mean, does this PR miss some commits already merged into master? I've updated the upmerge today morning, it should reflect current upstream master.

**Comment by ru-fu** [comment]
The doc build is red @carlescufi @rlubos :

WARNING: autodoc: failed to import module 'runners.core' the following exception was raised:

No module named 'runners'

/jenkins_workspace/workspace/ocumentation_test-zephyr-upmerge/_build/zephyr/rst/doc/tools/west/west-not-found.rst:6: WARNING: duplicate label west-apis, other instance in /jenkins_workspace/workspace/ocumentation_test-zephyr-upmerge/_build/zephyr/rst/doc/tools/west/west-apis.rst


tests.test_check_warnings: DEBUG: /jenkins_workspace/workspace/ocumentation_test-zephyr-upmerge/_build/nrf/rst/doc/nrf/samples/bluetooth/central_uart/README.rst:70: WARNING: undefined label: zephyr:kernel_apis (if the link has no caption the label must precede a section header)

/jenkins_workspace/workspace/ocumentation_test-zephyr-upmerge/_build/nrf/rst/doc/nrf/samples/bluetooth/central_uart/README.rst:74: WARNING: undefined label: zephyr:io_interfaces (if the link has no caption the label must precede a section header)

/jenkins_workspace/workspace/ocumentation_test-zephyr-upmerge/_build/nrf/rst/doc/nrf/samples/bluetooth/peripheral_hids_keyboard/README.rst:130: WARNING: undefined label: zephyr:io_interfaces (if the link has no caption the label must precede a section header)

/jenkins_workspace/workspace/ocumentation_test-zephyr-upmerge/_build/nrf/rst/doc/nrf/samples/bluetooth/peripheral_hids_mouse/README.rst:121: WARNING: undefined label: zephyr:io_interfaces (if the link has no caption the label must precede a section header)

/jenkins_workspace/workspace/ocumentation_test-zephyr-upmerge/_build/nrf/rst/doc/nrf/samples/bluetooth/peripheral_uart/README.rst:83: WARNING: undefined label: zephyr:kernel_apis (if the link has no caption the label must precede a section header)

/jenkins_workspace/workspace/ocumentation_test-zephyr-upmerge/_build/nrf/rst/doc/nrf/samples/bluetooth/peripheral_uart/README.rst:87: WARNING: undefined label: zephyr:io_interfaces (if the link has no caption the label must precede a section header)

/jenkins_workspace/workspace/ocumentation_test-zephyr-upmerge/_build/nrf/rst/doc/nrf/samples/bluetooth/throughput/README.rst:198: WARNING: undefined label: zephyr:kernel_apis (if the link has no caption the label must precede a section header)

**Comment by pdunaj** [comment]
It seems there are changes in power management that application needs to follow.
@pizi-nordic I have noticed that SYS_POWER_LOW_POWER_STATE_SUPPORTED is generally set on SoC level, while for Nordic chips it is not (though power manager sample selects it). Is this done on purpose?

**Comment by pdunaj** [comment]
Hi @rlubos , since you have PR already opened for upmerging issues could you add the following change there:
```
--- a/samples/nrf_desktop/src/modules/Kconfig.power_manager
+++ b/samples/nrf_desktop/src/modules/Kconfig.power_manager
@@ -10,6 +10,7 @@ config DESKTOP_POWER_MANAGER_ENABLE
        bool "Enable power management"
        default n
        select SYS_POWER_MANAGEMENT
+       select SYS_POWER_LOW_POWER_STATE_SUPPORTED
        select SYS_POWER_LOW_POWER_STATE
        select SYS_POWER_DEEP_SLEEP
        select DEVICE_POWER_MANAGEMENT
```

**Comment by pdunaj** [comment]
I got recursive spinlock on wakeup somewhere:
```
ASSERTION FAIL [(l->thread_cpu & 3) != (&_kernel.cpus[0])->id] @ /home/pdunaj/work/fw-nrfconnect-zephyr/include/spinlock.h:48
        Recursive spinlock
***** Kernel Panic! *****
Current thread ID = 0x20003fbc
Faulting instruction address = 0x75ac
```
Will look into that now

**Comment by pizi-nordic** [comment]
@pdunaj: At SoC level you have what the the SoC offers. However you are free to implement custom power states (for example: LED fully on or LED dimmed). In such case you need to define what additional power states are supported in your app.

**Comment by pdunaj** [comment]
I see another issue with the upmerge changes. It seems now CONFIG_FLASH_LOAD_SIZE and CONFIG_FLASH_LOAD_OFFSET are not properly set when MCUboot is enabled. It seems that DT_CODE_PARTITION_OFFSET=0 while it was set correctly before these changes.

**Comment by lemrey** [comment]
@pdunaj I have tried to build the throughput sample with `CONFIG_BOOTLOADER_MCUBOOT=y` and got:
`#define CONFIG_FLASH_LOAD_OFFSET 0xc000`
`#define CONFIG_FLASH_LOAD_SIZE 0x69000`

These values seem correct to me, is it a particular board that you are having troubles with?

**Comment by pdunaj** [comment]
@lemrey not dongle. I am checking pca20041.

**Comment by pdunaj** [comment]
Hi @rlubos , can you add one more change to the nrf PR:
```
--- a/boards/arm/nrf52840_pca20041/nrf52840_pca20041.dts
+++ b/boards/arm/nrf52840_pca20041/nrf52840_pca20041.dts
@@ -19,6 +19,7 @@
 #endif
                zephyr,sram = &sram0;
                zephyr,flash = &flash0;
+               zephyr,code-partition = &slot0_partition;
        };
 };
```

**Comment by lemrey** [comment]
I have checked with @pdunaj and found the root cause for the issue.
The issue is fixed by https://github.com/NordicPlayground/fw-nrfconnect-nrf/commit/fab9700132bf74a9c08a9e558790ee339d9e30f3

**Pull request merged**
