### PR TITLE
[DNM] [nrf mergeup] Merge upstream up to commit d6d7a80057

### PR DESCRIPTION
**Pull request by SebastianBoe**
Regular upmerge.

Merge conflicts that were resolved:

> Auto-merging subsys/dfu/boot/mcuboot.c
> CONFLICT (content): Merge conflict in subsys/dfu/boot/mcuboot.c
> Auto-merging ext/hal/nordic/nrfx_config_nrf9160.h
> CONFLICT (content): Merge conflict in ext/hal/nordic/nrfx_config_nrf9160.h
> Auto-merging ext/hal/nordic/nrfx_config_nrf52840.h
> CONFLICT (content): Merge conflict in ext/hal/nordic/nrfx_config_nrf52840.h
> Auto-merging ext/hal/nordic/nrfx_config_nrf52832.h
> CONFLICT (content): Merge conflict in ext/hal/nordic/nrfx_config_nrf52832.h
> Auto-merging ext/hal/nordic/nrfx_config_nrf52810.h
> CONFLICT (content): Merge conflict in ext/hal/nordic/nrfx_config_nrf52810.h
> Auto-merging ext/hal/nordic/nrfx_config_nrf51.h
> CONFLICT (content): Merge conflict in ext/hal/nordic/nrfx_config_nrf51.h
> CONFLICT (add/add): Merge conflict in ext/hal/nordic/nrfx/drivers/src/nrfx_nvmc.c
> Auto-merging ext/hal/nordic/nrfx/drivers/src/nrfx_nvmc.c
> CONFLICT (add/add): Merge conflict in ext/hal/nordic/nrfx/drivers/include/nrfx_nvmc.h
> Auto-merging ext/hal/nordic/nrfx/drivers/include/nrfx_nvmc.h
> Auto-merging ext/hal/nordic/nrfx/README
> CONFLICT (content): Merge conflict in ext/hal/nordic/nrfx/README
> Removing drivers/bluetooth/nrf51_pm.h
> Auto-merging doc/application/index.rst
> Auto-merging cmake/kconfig.cmake
> Auto-merging cmake/extensions.cmake
> Auto-merging cmake/dts.cmake
> CONFLICT (content): Merge conflict in cmake/dts.cmake
> Auto-merging cmake/app/boilerplate.cmake
> Auto-merging CODEOWNERS
> Auto-merging CMakeLists.txt
> Automatic merge failed; fix conflicts and then commit the result.

I diverged from the upmerge procedure by not reverting
6030b19718
e1d84eedd5
because they caused conflicts. And my intuition says it is
cleaner to resolve the conflicts in the merge commit.

### CODE REVIEW

**Comment by SebastianBoe** [comment]
I'm currently on step 8:

> Make sure CI passes on the manifest Pull Request

So no email has gone out yet.

**Comment by carlescufi** [comment]
> I diverged from the upmerge procedure by not reverting
> [6030b19](https://github.com/NordicPlayground/fw-nrfconnect-zephyr/commit/6030b19718ed65841f1e0213b2fc3ada026e1b19)
> [e1d84ee](https://github.com/NordicPlayground/fw-nrfconnect-zephyr/commit/e1d84eedd51657657ba3848de4b96b3e227daa49)
> because they caused conflicts. And my intuition says it is
> cleaner to resolve the conflicts in the merge commit.

I would like to hear  from @mbolivar , but the issue here if you don't revert them is that they will still appear as out-of-tree to the script that we will soon introduce to help us track out-of-tree commits

**Comment by rlubos** [comment]
The checkpatch/codeowners failures seem to be inherited from the upstream.

As for the codeowners:

```
ERROR   : Test Codeowners failed: New files added that are not covered in CODEOWNERS:

samples/boards/nrf52/mesh/onoff_level_lighting_vnd_app/prj_smp_svr.conf
samples/boards/nrf52/mesh/onoff_level_lighting_vnd_app/src/smp_svr.c
samples/boards/nrf52/mesh/onoff_level_lighting_vnd_app/src/smp_svr.h
```

For whatever reason this PR got in without checking for the codeowners coverage:
https://github.com/zephyrproject-rtos/zephyr/pull/13135

checkpatch throws lots of errors from some `svg` files:

```
-:4244: ERROR:DOS_LINE_ENDINGS: DOS line endings
#4244: FILE: boards/arm/nrf52840_pca10059/doc/img/nRF52840_dongle_press_reset.svg:1807:
+^I^I129.27,18.09 143.79,18.21 129.69,43.11 ^I"/>^M$
```

These seemed ignored in this PR:
https://github.com/zephyrproject-rtos/zephyr/pull/15474

**Comment by rlubos** [comment]
So regarding https://github.com/NordicPlayground/fw-nrfconnect-zephyr/pull/134#issuecomment-485253794, @carlescufi @mbolivar @SebastianBoe we need to settle whether to revert or not. Otherwise, this PR is good to go IMO.

**Comment by SebastianBoe** [comment]
IMHO the tool to track out-of-tree commits needs a whitelist for the cases it is not able to automatically detect.

**Comment by mbolivar** [comment]
Reverting is better in the long term because it makes rebasing easier. If this branch were going to live forever without rebasing I would agree resolving in the merge commit would be better.

**Comment by carlescufi** [comment]
Let's try to revert them @SebastianBoe @rlubos. If that fails then let's fall back to solving it in the merge

**Comment by rlubos** [comment]
I've reverted more commits that are already present in the upstream, the merge itself was not that bad, only 2 conflicts:
```
Auto-merging subsys/dfu/boot/mcuboot.c
CONFLICT (content): Merge conflict in subsys/dfu/boot/mcuboot.c
Removing drivers/bluetooth/nrf51_pm.h
Auto-merging doc/application/index.rst
Auto-merging cmake/kconfig.cmake
Auto-merging cmake/extensions.cmake
Auto-merging cmake/dts.cmake
CONFLICT (content): Merge conflict in cmake/dts.cmake
Auto-merging cmake/app/boilerplate.cmake
Auto-merging CODEOWNERS
Auto-merging CMakeLists.txt
Automatic merge failed; fix conflicts and then commit the result.
```

Note that one `[nrf noup]` was reverted as it produced conflicts during other reverts. The change in there was straightforward and was reinstated in the merge commit.

Technically the diff between current branch and the previous approach is empty. Only the commit arrangement changed.

**Pull request merged**
