### PR TITLE
[nrf ci] ci: switch sanitycheck to gnuarmemb and run in parallel on 4 machines. 

### PR DESCRIPTION
**Pull request by thst-nordic**
DNM: testing gnuarmemb patch

### CODE REVIEW

**Comment by thst-nordic** [comment]
This has the upstream patch that fixes gnuarmemb typedef, and all sanity-check compiles. 
https://jenkins-ncs.nordicsemi.no/blue/organizations/jenkins/fw-nrfconnect-zephyr/detail/PR-199/9/pipeline/75

**Comment by carlescufi** [comment]
Thanks @thst-nordic . Seems to work. Note that the `[fromlist]` patch was already included by @mbolivar  in https://github.com/NordicPlayground/fw-nrfconnect-zephyr/pull/197.

This is green, nice job!

**Comment by carlescufi** [comment]
@mbolivar @thst-nordic should we merge this as-is or remove the `[fromlist]` patch?

**Comment by mbolivar** [comment]
> @mbolivar @thst-nordic should we merge this as-is or remove the `[fromlist]` patch?

We've been talking about an [nrf ci] tag, but we don't currently have one. I would prefer not to start adding one now. Let's wait until the next rebase and rewrite all the CI shortlogs to use it instead, so [nrf noup] for now.

Let's also drop the fromlist since it's included in the mergeup.

**Comment by carlescufi** [comment]
Already in mergeup PR

**Pull request closed without merging**
