### PR TITLE
Fix s1 variant

### PR DESCRIPTION
**Pull request by SebastianBoe**
This PR makes the attached code compatible with both ncs master and with the upcoming re-write of multi-image.

This is done to reduce the size of the re-write PR.

Details of the changes are in the commit messages.

### CODE REVIEW

**Comment by tejlmand** [comment]
Just noticed.
Although this is a small patch, would it be preferable to do a revert of: 
https://github.com/NordicPlayground/fw-nrfconnect-zephyr/commit/bfd1ae364c01fbe576d36ee21af00cdeb87feb6c

and then a re-apply, including the proposed changes as a single [nrf noup] ?
In order to keep the number of [nrf noup] patches as small as possible.

Afterall, this PR introduces 3 new [nrf noup] + plus the existing.

@mbolivar thoughts ?

**Comment by SebastianBoe** [comment]
I don't have a good enough understanding of the upmerge procedure to say if this makes sense or not.

**Comment by tejlmand** [comment]
> 
> 
> I don't have a good enough understanding of the upmerge procedure to say if this makes sense or not.

me neither, that's why I asked for @mbolivar comments ;)

**Comment by mbolivar** [comment]
> > I don't have a good enough understanding of the upmerge procedure to say if this makes sense or not.
> 
> me neither, that's why I asked for @mbolivar comments ;)

If you want to keep the west ncs-loot output clean, revert and reapply is nice. But for something like this, where we're basically replacing one patch series with another, I think I might just do a bunch of squashing at the next rebase anyway, so don't worry too much about reverts if they are really slowing you down. Just please keep commits logically separate so they can be rebased around later and I'll be grateful :).

**Comment by mbolivar** [comment]
> Although this is a small patch, would it be preferable to do a revert of:
> [bfd1ae3](https://github.com/NordicPlayground/fw-nrfconnect-zephyr/commit/bfd1ae364c01fbe576d36ee21af00cdeb87feb6c)


FTR, looking at that patch again, I see this comment:

```
# Create second MCUBoot executable for the second slot of the second stage
# bootloader. This is done inside this file since it is non-trivial to add
# executable targets outside the root CMakeLists.txt. The problem is that
# most of the variables requried for compiling/linking is only available
# in the scope of this file.
```

Above, "this file" is zephyr/CMakeLists.txt. I think this is evidence that defining the zephyr executable in there instead of boilerplate forces users to edit this file when they might prefer not to. It's certainly a layering violation.

**Comment by SebastianBoe** [comment]
>  I think this is evidence that defining the zephyr executable in there instead of boilerplate forces users to edit this file when they might prefer not to. It's certainly a layering violation.

You might be right about that, I should look into this later.

**Pull request merged**
