### PR TITLE
Upmerge 09 March 2020

### PR DESCRIPTION
**Pull request by emob-nordic**
Regular upmerge.

### CODE REVIEW

**Comment by mbolivar-nordic** [comment]
Great work!

These downstream patches are no longer needed and should be reverted before the mergeup:

- 4f020657c5:  was merged upstream as 8629f0a4507b84480af1c6b5b1d298d392cc4e77
- 7f33c8036148a1d67042e78ee7870ad952549f1b:  was merged upstream as bdc535dba3d9dc8ac5e372aa01d2ec9912759f10

Otherwise, I've prepared a rebase branch here by cherry-picking the `west ncs-loot` output for this PR as of commit 5c4924ae01 on top of v2.2.0:

https://github.com/mbolivar-nordic/fw-nrfconnect-zephyr/tree/mergeup-288-rebase

I had to skip the cherry-picks for those two patches, but the trees are identical after doing that, so this looks good structurally other than that.

I needed a patch to west ncs-loot to get this output which I will post separately.

**Comment by emob-nordic** [comment]
> Great work!
> 
> These downstream patches are no longer needed and should be reverted before the mergeup:
> 
> * [4f02065](https://github.com/NordicPlayground/fw-nrfconnect-zephyr/commit/4f020657c50a071105cb7b673d74c29734ca7408):  was merged upstream as [8629f0a](https://github.com/NordicPlayground/fw-nrfconnect-zephyr/commit/8629f0a4507b84480af1c6b5b1d298d392cc4e77)
> * [7f33c80](https://github.com/NordicPlayground/fw-nrfconnect-zephyr/commit/7f33c8036148a1d67042e78ee7870ad952549f1b):  was merged upstream as [bdc535d](https://github.com/NordicPlayground/fw-nrfconnect-zephyr/commit/bdc535dba3d9dc8ac5e372aa01d2ec9912759f10)
> 
> Otherwise, I've prepared a rebase branch here by cherry-picking the `west ncs-loot` output for this PR as of commit [5c4924a](https://github.com/NordicPlayground/fw-nrfconnect-zephyr/commit/5c4924ae013fa786e5179b7bc5c4cab928c957ac) on top of v2.2.0:
> 
> https://github.com/mbolivar-nordic/fw-nrfconnect-zephyr/tree/mergeup-288-rebase
> 
> I had to skip the cherry-picks for those two patches, but the trees are identical after doing that, so this looks good structurally other than that.
> 
> I needed a patch to west ncs-loot to get this output which I will post separately.
> Edit: posted [NordicPlayground/fw-nrfconnect-nrf#2087](https://github.com/NordicPlayground/fw-nrfconnect-nrf/pull/2087)

I will revert those 2 patches You mentioned but I dont get what do You mean with that rebase branch? Should we actually update this at all or use Your upmerge branch or what?

**Comment by mbolivar-nordic** [comment]
> I dont get what do You mean with that rebase branch? Should we actually update this at all or use Your upmerge branch or what?

No no, don't use it here; it's not time to rebase yet.

I post a rebase as a review comment every time we merge upstream, because:

- I do it anyway while I'm reviewing to check for missing reverts, and it's a hint to the submitter for how they can do the same check in the future
- It's evidence that the mergeup is good
- So the submitter has a chance to see why they have to follow all of those silly sauce tag rules: "because it makes it possible to rebase easily, and this rebase is proof"
- For my own benefit in case we have to rebase in an emergency, to have something to start with

**Comment by tejlmand** [comment]
> 
> 
> Why build smp_svr @nrf52840_pca10056 is not multi-mage build anymore?
> @hakonfam Any clue?
> or @tejlmand
> 
> [edt]
> at last nrf9160_pca10090 is affected as well :(

Sound wrong.
Will take a look.

**Comment by tejlmand** [comment]
> > Why build smp_svr @nrf52840_pca10056 is not multi-mage build anymore?
> > @hakonfam Any clue?
> > or @tejlmand
> > [edt]
> > at last nrf9160_pca10090 is affected as well :(
> 
> Sound wrong.
> Will take a look.

This looks ok to me:
```
> cmake -GNinja -DBOARD=nrf9160_pca10090ns -Bbuild .
-- Zephyr version: 2.2.0
-- Selected BOARD nrf9160_pca10090ns
-- Found west: /home/tora/.local/bin/west (found suitable version "0.7.2", minimum required is "0.6.0")
-- Loading /projects/github/ncs/zephyr/boards/arm/nrf9160_pca10090/nrf9160_pca10090ns.dts as base
Devicetree header saved to '/projects/github/ncs/nrf/applications/asset_tracker/build/zephyr/include/generated/devicetree_unfixed.h'
Parsing /projects/github/ncs/nrf/applications/asset_tracker/Kconfig
/projects/github/ncs/nrf/lib/fprotect/Kconfig:28: WARNING: dt_hex_val is deprecated.
/projects/github/ncs/bootloader/mcuboot/zephyr/Kconfig:37: WARNING: dt_int_val is deprecated.
Loaded configuration '/projects/github/ncs/zephyr/boards/arm/nrf9160_pca10090/nrf9160_pca10090ns_defconfig'
Merged configuration '/projects/github/ncs/nrf/applications/asset_tracker/prj.conf'
Configuration saved to '/projects/github/ncs/nrf/applications/asset_tracker/build/zephyr/.config'
Kconfig header saved to '/projects/github/ncs/nrf/applications/asset_tracker/build/zephyr/include/generated/autoconf.h'
-- The C compiler identification is GNU 7.3.1
-- The CXX compiler identification is GNU 7.3.1
-- The ASM compiler identification is GNU
-- Found assembler: /opt/gcc-arm-none-eabi-7-2018-q2-update/bin/arm-none-eabi-gcc
-- Cache files will be written to: /home/tora/.cache/zephyr

=== child image spm begin ===
Changed board to secure nrf9160_pca10090 (NOT NS)
-- Zephyr version: 2.2.0
-- Found PythonInterp: /usr/bin/python3.6 (found suitable version "3.6.8", minimum required is "3.6") 
-- Selected BOARD nrf9160_pca10090
-- Found west: /home/tora/.local/bin/west (found suitable version "0.7.2", minimum required is "0.6.0")
-- Loading /projects/github/ncs/zephyr/boards/arm/nrf9160_pca10090/nrf9160_pca10090.dts as base
-- Overlaying /projects/github/ncs/nrf/samples/nrf9160/spm/nrf9160_pca10090.overlay
Devicetree header saved to '/projects/github/ncs/nrf/applications/asset_tracker/build/spm/zephyr/include/generated/devicetree_unfixed.h'
Parsing /projects/github/ncs/zephyr/Kconfig
/projects/github/ncs/nrf/lib/fprotect/Kconfig:28: WARNING: dt_hex_val is deprecated.
/projects/github/ncs/bootloader/mcuboot/zephyr/Kconfig:37: WARNING: dt_int_val is deprecated.
Loaded configuration '/projects/github/ncs/zephyr/boards/arm/nrf9160_pca10090/nrf9160_pca10090_defconfig'
Merged configuration '/projects/github/ncs/nrf/applications/asset_tracker/spm.conf'
Configuration saved to '/projects/github/ncs/nrf/applications/asset_tracker/build/spm/zephyr/.config'
Kconfig header saved to '/projects/github/ncs/nrf/applications/asset_tracker/build/spm/zephyr/include/generated/autoconf.h'
-- The C compiler identification is GNU 7.3.1
-- The CXX compiler identification is GNU 7.3.1
-- The ASM compiler identification is GNU
-- Found assembler: /opt/gcc-arm-none-eabi-7-2018-q2-update/bin/arm-none-eabi-gcc
-- Cache files will be written to: /home/tora/.cache/zephyr
-- Configuring done
-- Generating done
-- Build files have been written to: /projects/github/ncs/nrf/applications/asset_tracker/build/spm
=== child image spm end ===


=== child image mcuboot begin ===

```

**Pull request merged**
