### PR TITLE
 cortex_m: linker.ld: Add wildcard and sort to fw_info

### PR DESCRIPTION
**Pull request by oyvindronningstad**
One commit has already gone into master in #251. The current changes will be revised if not merged when the next upmerge happens.

### CODE REVIEW

**Comment by sigvartmh** [comment]
That's done https://github.com/NordicPlayground/fw-nrfconnect-nrf/blob/1d8b907d6f073d1f0d7180f3a07a70a5b2efa58c/subsys/fw_info/CMakeLists.txt#L9 here right?

**Comment by oyvindronningstad** [comment]
> That's done https://github.com/NordicPlayground/fw-nrfconnect-nrf/blob/1d8b907d6f073d1f0d7180f3a07a70a5b2efa58c/subsys/fw_info/CMakeLists.txt#L9 here right?

Yep

**Comment by oyvindronningstad** [comment]
> DNM until [NordicPlayground/fw-nrfconnect-nrf#1378](https://github.com/NordicPlayground/fw-nrfconnect-nrf/pull/1378) is merged or equivalent PR

This needs to go in first so west.yml can be fixed in NordicPlayground/fw-nrfconnect-nrf#1378.

**Comment by hakonfam** [comment]
So stuff will be broken between the time between this is merged and  NordicPlayground/fw-nrfconnect-nrf#1378 is merged?

**Comment by oyvindronningstad** [comment]
> So stuff will be broken between the time between this is merged and [NordicPlayground/fw-nrfconnect-nrf#1378](https://github.com/NordicPlayground/fw-nrfconnect-nrf/pull/1378) is merged?

It's like it always is when merging something into fw-nrfconnect-zephyr. We'll try to merge this right before, update west.yml, and then merge NordicPlayground/fw-nrfconnect-nrf#1378.

**Comment by hakonfam** [comment]
Got it, adding DNM label so that this is not merged by accident until the other PR is ready to merge then :)

**Comment by mbolivar** [comment]
> > So stuff will be broken between the time between this is merged and [NordicPlayground/fw-nrfconnect-nrf#1378](https://github.com/NordicPlayground/fw-nrfconnect-nrf/pull/1378) is merged?
> 
> It's like it always is when merging something into fw-nrfconnect-zephyr. We'll try to merge this right before, update west.yml, and then merge [NordicPlayground/fw-nrfconnect-nrf#1378](https://github.com/NordicPlayground/fw-nrfconnect-nrf/pull/1378).

What will be "broken", exactly? I'm confused.

The reason we use SHAs as revisions in west.yml is so we can update the entire NCS atomically with a single commit to nrf. Changes from other repositories are done by updating the SHAs. So although master/master might not work from time to time, that's not what's being distributed to others.

**Comment by oyvindronningstad** [comment]
> This looks like a straightforward revert of [4cc4339](https://github.com/NordicPlayground/fw-nrfconnect-zephyr/commit/4cc4339719d422995e65a48c09b8ed6572505bd4); why not just use 'git revert' so that 'west ncs-loot' knows the patch is gone? That way it will disappear entirely in the next rebase.

Good point, will change to revert.

**Comment by mbolivar** [comment]
History in this repository has been rewritten. Please rebase this PR.

**Comment by mbolivar** [comment]
> > This looks like a straightforward revert of [4cc4339](https://github.com/NordicPlayground/fw-nrfconnect-zephyr/commit/4cc4339719d422995e65a48c09b8ed6572505bd4); why not just use 'git revert' so that 'west ncs-loot' knows the patch is gone? That way it will disappear entirely in the next rebase.
> 
> Good point, will change to revert.

Looks like this is no longer true, so I'm dismissing my review as it applied to another patch.

**Comment by mbolivar** [comment]
@oyvindronningstad I am not sure, but I think @anangl may be planning to revert b0b08e853c5942bda1a2204e34101388cb4d3e8f and replace it with a use of zephyr_linker_sources() in the merge he is working on right now -- it's probably worth aligning on this.

**Comment by oyvindronningstad** [comment]
> @oyvindronningstad I am not sure, but I think @anangl may be planning to revert [b0b08e8](https://github.com/NordicPlayground/fw-nrfconnect-zephyr/commit/b0b08e853c5942bda1a2204e34101388cb4d3e8f) and replace it with a use of zephyr_linker_sources() in the merge he is working on right now -- it's probably worth aligning on this.

@mbolivar Ok, that's great, I would be doing that on the next upmerge if he didn't.

@anangl How far along are you with the upmerge?

**Comment by anangl** [comment]
> > @oyvindronningstad I am not sure, but I think @anangl may be planning to revert [b0b08e8](https://github.com/NordicPlayground/fw-nrfconnect-zephyr/commit/b0b08e853c5942bda1a2204e34101388cb4d3e8f) and replace it with a use of zephyr_linker_sources() in the merge he is working on right now -- it's probably worth aligning on this.
> 
> @mbolivar Ok, that's great, I would be doing that on the next upmerge if he didn't.
> 
> @anangl How far along are you with the upmerge?

@oyvindronningstad I prepared a [branch](https://github.com/anangl/fw-nrfconnect-zephyr/commits/upmerge_16_01_2020) where b0b08e853c5942bda1a2204e34101388cb4d3e8f is [reverted](https://github.com/anangl/fw-nrfconnect-zephyr/commit/cb5a89090472bb33be1ce515e386f38b2b0c42b7). I'm not sure yet how the replacement for it that uses `zephyr_linker_sources` should look like.

**Comment by oyvindronningstad** [comment]
> > > @oyvindronningstad I am not sure, but I think @anangl may be planning to revert [b0b08e8](https://github.com/NordicPlayground/fw-nrfconnect-zephyr/commit/b0b08e853c5942bda1a2204e34101388cb4d3e8f) and replace it with a use of zephyr_linker_sources() in the merge he is working on right now -- it's probably worth aligning on this.
> > 
> > 
> > @mbolivar Ok, that's great, I would be doing that on the next upmerge if he didn't.
> > @anangl How far along are you with the upmerge?
> 
> @oyvindronningstad I prepared a [branch](https://github.com/anangl/fw-nrfconnect-zephyr/commits/upmerge_16_01_2020) where [b0b08e8](https://github.com/NordicPlayground/fw-nrfconnect-zephyr/commit/b0b08e853c5942bda1a2204e34101388cb4d3e8f) is [reverted](https://github.com/anangl/fw-nrfconnect-zephyr/commit/cb5a89090472bb33be1ce515e386f38b2b0c42b7). I'm not sure yet how the replacement for it that uses `zephyr_linker_sources` should look like.

Great!
I think the call should be something like

    zephyr_linker_sources_ifdef(CONFIG_FW_INFO TEXT_START SORT_KEY ${CONFIG_FW_INFO_OFFSET} fw_info.ld)

**Comment by anangl** [comment]
> Great!
> I think the call should be something like
> 
> ```
> zephyr_linker_sources_ifdef(CONFIG_FW_INFO TEXT_START SORT_KEY ${CONFIG_FW_INFO_OFFSET} fw_info.ld)
> ```

Thanks, I'll try with this. Need to finish preparing mcuboot upmerge still. Then I'll create the PR to the nrf repo that will make use of all these changes.

**Comment by mbolivar** [comment]
DNM until #261

**Comment by oyvindronningstad** [comment]
Upmerge is now in. This change can now be done in the nrf repo

**Pull request closed without merging**
