### PR TITLE
[nrf fromlist] boards: thingy53: start network core before 802.15.4 driver

### PR DESCRIPTION
**Pull request by Damian-Nordic**
The nRF5 802.15.4 driver tries to establish a rpmsg channel
with the network core, so the network core must be started
earlier. Therefore, decrease the priority level of the task
responsible for initializing the Thingy:53 board.

Signed-off-by: Damian Krolik <damian.krolik@nordicsemi.no>

### CODE REVIEW

**Review by eobalski — CHANGES_REQUESTED** [review]
Blocking as this should not go in before upstream PR [#36587](https://github.com/zephyrproject-rtos/zephyr/pull/36587). btw this PR should be exact copy of the one already mentioned with [fromlist] label in the commit message. Do not change anything in the commit message besides that. It later on complicates upmerge. Wait for 36587 to be merged and then cherry-pick that commit to this PR.

**Comment by Damian-Nordic** [comment]
@emob-nordic https://github.com/zephyrproject-rtos/zephyr/pull/36587 is merged, can this PR be unblocked?

**Comment by emob-nordic** [comment]
Actually yes, seems my block does not count anyway :p

**Review by eobalski — APPROVED** [review]

**Comment by emob-nordic** [comment]
@anangl Can we merge this or we shall wait for upmerge?

**Review by MarekPieta — APPROVED** [review]
Looks good.
btw. Should we use [nrf fromtree] since the change was already merged in Zephyr?

**Comment by Damian-Nordic** [comment]
> Looks good.
> btw. Should we use [nrf fromtree] since the change was already merged in Zephyr?

Yes, done.

**Review by joerchan — APPROVED** [review]

**Review by anangl — APPROVED** [review]

**Pull request merged**
