### PR TITLE
IMAGEify extra_post_build_byproducts

### PR DESCRIPTION
**Pull request by oyvindronningstad**
This should not be merged until the fromlist commits can be rebased away.

Also: IMAGEify extra_post_build_byproducts

### CODE REVIEW

**Comment by oyvindronningstad** [comment]
Companion to https://github.com/NordicPlayground/fw-nrfconnect-nrf/pull/753

**Comment by oyvindronningstad** [comment]
@SebastianBoe, this PR is now ready for review.
cc @hakonfam @ioannisg

**Comment by SebastianBoe** [comment]
> Why can't this go upstream, directly?

It depends on multi-image.

**Comment by ioannisg** [comment]
@SebastianBoe thanks. I saw, also the [toup] tag now.

**Comment by oyvindronningstad** [comment]
Ready to merge

**Comment by SebastianBoe** [comment]
@oyvindronningstad : FYI; CI failure

**Comment by oyvindronningstad** [comment]
> @oyvindronningstad : FYI; CI failure

Leftover from mergeup. Let's wait until it's fixed.

**Pull request merged**
